name: ZS-StaffMenu
api: [3.0.0-ALPHA12, 3.0.0-ALPHA12-ALPHA4, 3.0.0-ALPHA12-ALPHA5, 3.0.0-ALPHA12-ALPHA12] 
version: "1.0.0-Beta"
main: NewZerosjm\StaffMenu
author: MineDefenser
website: http://zerosm.kro.kr